import { useEffect, useState } from 'react';
import { navigate } from '../lib/router';
import { storage } from '../lib/storage';
import { useAudit } from '../hooks/useAudit';
import { 
  RotateCcw, 
  ArrowRight, 
  FileText, 
  Check, 
  ShieldCheck, 
  ArrowLeft,
  Sparkles,
  Inbox,
  Link as LinkIcon,
  Download
} from 'lucide-react';

// Subcomponents
import SavingsHero from '../components/results/SavingsHero';
import ExecutiveSummary from '../components/results/ExecutiveSummary';
import Recommendations from '../components/results/Recommendations';
import SpendComparison from '../components/results/SpendComparison';
import StackHealthScore from '../components/results/StackHealthScore';

export default function ResultsPage({ reportId }) {
  const { 
    loading: dbLoading, 
    error: dbError, 
    saveAuditReport, 
    fetchAuditReport, 
    submitLead 
  } = useAudit();

  const [auditInput, setAuditInput] = useState(null);
  const [auditResult, setAuditResult] = useState(null);
  const [email, setEmail] = useState('');
  const [company, setCompany] = useState('');
  const [role, setRole] = useState('');
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [currentReportId, setCurrentReportId] = useState(reportId || null);
  const [toastMessage, setToastMessage] = useState(null);
  const [hasSaved, setHasSaved] = useState(false);

  // Generate unique 6-character report ID (e.g. 7f9d4k)
  const generateShortId = () => {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    for (let i = 0; i < 6; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  };

  useEffect(() => {
    const initPage = async () => {
      if (reportId) {
        // Mode 1: Fetching an existing report from Supabase by reportId
        const report = await fetchAuditReport(reportId);
        if (report) {
          setAuditInput(report.audit_input);
          // Reconstruct the result structure expected by the page components
          setAuditResult({
            monthlySavings: report.monthly_savings,
            annualSavings: report.yearly_savings,
            recommendations: report.recommendations,
            summary: {
              wasteScore: report.audit_score,
              stackEfficiency: report.audit_score > 35 ? 'Low' : report.audit_score > 15 ? 'Moderate' : 'Optimal',
              opportunitiesFound: report.recommendations.length,
              totalSpend: (report.audit_input.tools || []).reduce((sum, t) => sum + (t.monthlySpend || 0), 0)
            }
          });
          setCurrentReportId(reportId);
        }
      } else {
        // Mode 2: Loading fresh results just generated by user
        const cachedInput = storage.loadAuditInput();
        const cachedResult = storage.loadAuditResult();

        if (cachedInput && cachedResult) {
          setAuditInput(cachedInput);
          setAuditResult(cachedResult);

          // Auto-save the fresh report once to Supabase
          if (!hasSaved) {
            setHasSaved(true);
            const newId = generateShortId();
            const success = await saveAuditReport(newId, cachedInput, cachedResult);
            if (success) {
              setCurrentReportId(newId);
              // Save ID in local storage as current session backup
              localStorage.setItem('sift_last_report_id', newId);
            }
          }
        }
      }
    };

    initPage();
  }, [reportId, fetchAuditReport, saveAuditReport, hasSaved]);

  const handleEmailSubmit = async (e) => {
    e.preventDefault();
    if (email.trim() && email.includes('@')) {
      const success = await submitLead(email, company, role, auditInput, auditResult);
      if (success) {
        setIsSubmitted(true);
        setTimeout(() => {
          setEmail('');
          setCompany('');
          setRole('');
        }, 5000);
      }
    }
  };

  const handleRunAnother = () => {
    storage.clearAuditInput();
    storage.clearAuditResult();
    localStorage.removeItem('sift_last_report_id');
    navigate('/audit');
  };

  const handleCopyLink = () => {
    const idToCopy = currentReportId || localStorage.getItem('sift_last_report_id') || 'temp';
    const reportUrl = `${window.location.origin}/report/${idToCopy}`;
    navigator.clipboard.writeText(reportUrl)
      .then(() => {
        setToastMessage("Link copied");
        setTimeout(() => setToastMessage(null), 3000);
      })
      .catch((err) => {
        console.error('Failed to copy link:', err);
      });
  };

  const handleExportSummary = () => {
    if (!auditInput || !auditResult) return;
    
    const idToUse = currentReportId || localStorage.getItem('sift_last_report_id') || 'temp';
    let text = `========================================\n`;
    text += `SIFT AI SPEND AUDIT REPORT\n`;
    text += `Generated on: ${new Date().toLocaleDateString()}\n`;
    text += `Report ID: ${idToUse}\n`;
    text += `Shareable URL: ${window.location.origin}/report/${idToUse}\n`;
    text += `========================================\n\n`;
    
    text += `EXECUTIVE SUMMARY\n`;
    text += `----------------------------------------\n`;
    text += `Team Size: ${auditInput.teamSize} members\n`;
    text += `Primary Use Case: ${auditInput.primaryUseCase}\n`;
    text += `Total Current Spend: $${auditResult.summary.totalSpend}/mo\n`;
    text += `Estimated Monthly Savings: $${auditResult.monthlySavings}/mo\n`;
    text += `Estimated Annual Savings: $${auditResult.annualSavings}/yr\n`;
    text += `Waste Score: ${auditResult.summary.wasteScore}%\n`;
    text += `Efficiency Rating: ${auditResult.summary.stackEfficiency}\n\n`;
    
    text += `OPTIMIZATION RECOMMENDATIONS (${auditResult.recommendations.length} found)\n`;
    text += `----------------------------------------\n`;
    auditResult.recommendations.forEach((rec, idx) => {
      text += `${idx + 1}. [${rec.severity.toUpperCase()}] ${rec.tool}: ${rec.title}\n`;
      text += `   Reason: ${rec.reason}\n`;
      text += `   Potential Savings: $${rec.monthlySavings}/mo\n\n`;
    });
    
    text += `========================================\n`;
    text += `Secured by Sift Cost Intelligence Inc.\n`;
    
    const element = document.createElement("a");
    const file = new Blob([text], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `sift_ai_audit_${idToUse}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  // Premium database loading state
  if (dbLoading && !auditInput) {
    return (
      <div className="empty-results-screen">
        <div className="glow-mesh-overlay"></div>
        <div className="empty-state-card animated-card" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '16px' }}>
          <div className="dash-spinner" style={{ width: '32px', height: '32px' }}></div>
          <h2 className="empty-title">Retrieving Audit Report...</h2>
          <p className="empty-description">Connecting securely to Supabase to fetch optimization parameters.</p>
        </div>
      </div>
    );
  }

  // Elegant empty state if no report is found or error occurs
  if ((!auditInput || !auditResult) && !dbLoading) {
    return (
      <div className="empty-results-screen">
        <div className="glow-mesh-overlay"></div>
        
        <div className="empty-state-card animated-card">
          <div className="empty-icon-box">
            <Inbox size={32} className="text-dim" />
          </div>
          <h2 className="empty-title">Audit Report Not Found</h2>
          <p className="empty-description">
            {dbError ? `Error: ${dbError}` : "We couldn't retrieve the specified spend audit. It may have expired or the report ID is invalid."}
          </p>
          <div className="empty-actions">
            <button 
              onClick={() => navigate('/audit')} 
              className="btn-primary"
            >
              <span>Start Free Audit</span>
              <ArrowRight size={14} />
            </button>
            <button 
              onClick={() => navigate('/')} 
              className="btn-secondary"
            >
              Back to Home
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="results-page-wrapper">
      <div className="glow-mesh-overlay"></div>

      <section className="section-container" style={{ paddingTop: '110px', paddingBottom: '80px' }}>
        {/* Navigation Breadcrumb */}
        <div className="breadcrumb-nav">
          <button onClick={() => navigate('/')} className="back-link-btn">
            <ArrowLeft size={13} />
            <span>Home</span>
          </button>
          <span className="bread-sep">/</span>
          <span className="bread-active">Spend Report</span>
          {currentReportId && (
            <>
              <span className="bread-sep">/</span>
              <span className="bread-active font-mono" style={{ color: 'var(--accent-soft)' }}>#{currentReportId}</span>
            </>
          )}
        </div>

        {/* Upgrade Header */}
        <div className="results-header-box" style={{ marginBottom: '32px' }}>
          <h1 className="title-large" style={{ fontSize: '44px', marginBottom: '12px', textAlign: 'left', marginLeft: 0 }}>
            Subscription Cost Recovery Report
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '15px', maxWidth: '720px' }}>
            We analyzed <strong>{auditInput.tools.length}</strong> active platform integrations across your enterprise team of <strong>{auditInput.teamSize}</strong> members using Sift Cost Optimization Engine.
          </p>
        </div>

        {/* Premium Layout */}
        <div className="results-layout-grid">
          
          {/* Main Hero Card Span */}
          <div className="results-hero-span">
            <SavingsHero 
              annualSavings={auditResult.annualSavings}
              monthlySavings={auditResult.monthlySavings}
              opportunitiesFound={auditResult.summary.opportunitiesFound}
            />
          </div>

          {/* Left Column: Summary & Specific Action Recommendations */}
          <div className="results-main-col">
            <ExecutiveSummary 
              recommendations={auditResult.recommendations}
              wasteScore={auditResult.summary.wasteScore}
              stackEfficiency={auditResult.summary.stackEfficiency}
              auditInput={auditInput}
              auditResult={auditResult}
            />

            <Recommendations 
              recommendations={auditResult.recommendations}
            />
          </div>

          {/* Right Column: Comparative projections, Health scales, and PDF Dispatcher */}
          <div className="results-side-col">
            <StackHealthScore 
              wasteScore={auditResult.summary.wasteScore}
            />

            <SpendComparison 
              totalSpend={auditResult.summary.totalSpend}
              monthlySavings={auditResult.monthlySavings}
              annualSavings={auditResult.annualSavings}
            />

            {/* Save Report / PDF Dispatch Box */}
            <div className="results-optimizations-panel dispatch-pdf-card">
              <div className="pdf-decor-circle"></div>
              <h4 className="dispatch-title">
                <Sparkles size={14} className="accent-text-icon" />
                <span>Save Report &amp; Get PDF</span>
              </h4>
              <p className="dispatch-desc">
                Enter your enterprise email to save this report in the cloud and schedule a full SOC2 cost optimization PDF.
              </p>

              <div className="dispatch-action-group">
                {!isSubmitted ? (
                  <form onSubmit={handleEmailSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '10px', width: '100%' }}>
                    <input
                      type="email"
                      required
                      placeholder="enter enterprise email *"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      className="cta-input-field"
                      style={{ width: '100%', fontSize: '13px', padding: '12px 14px', background: '#09090b' }}
                    />
                    <input
                      type="text"
                      placeholder="company (optional)"
                      value={company}
                      onChange={(e) => setCompany(e.target.value)}
                      className="cta-input-field"
                      style={{ width: '100%', fontSize: '13px', padding: '12px 14px', background: '#09090b' }}
                    />
                    <input
                      type="text"
                      placeholder="your role (e.g. CTO) (optional)"
                      value={role}
                      onChange={(e) => setRole(e.target.value)}
                      className="cta-input-field"
                      style={{ width: '100%', fontSize: '13px', padding: '12px 14px', background: '#09090b' }}
                    />
                    <button type="submit" className="btn-primary" style={{ width: '100%', padding: '12px 14px', fontSize: '13px', justifyContent: 'center' }}>
                      <FileText size={14} />
                      <span>Dispatch PDF Report</span>
                    </button>
                  </form>
                ) : (
                  <div className="cta-micro-feedback" style={{ padding: '12px', background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.2)', borderRadius: '6px', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '8px', color: '#10b981', width: '100%' }}>
                    <Check size={14} />
                    <span>Your audit report has been saved.</span>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Action Row */}
        <div className="results-action-row" style={{ marginTop: '48px', display: 'flex', justifyContent: 'space-between', borderTop: '1px solid var(--border-primary)', paddingTop: '24px', flexWrap: 'wrap', gap: '16px' }}>
          <div style={{ display: 'flex', gap: '12px' }}>
            <button
              onClick={() => navigate('/')}
              className="btn-secondary"
              style={{ padding: '10px 20px', fontSize: '13px' }}
            >
              Return to Dashboard
            </button>

            <button
              onClick={handleCopyLink}
              className="btn-secondary"
              style={{ padding: '10px 20px', fontSize: '13px', gap: '6px' }}
            >
              <LinkIcon size={13} />
              <span>Copy Report Link</span>
            </button>

            <button
              onClick={handleExportSummary}
              className="btn-secondary"
              style={{ padding: '10px 20px', fontSize: '13px', gap: '6px' }}
            >
              <Download size={13} />
              <span>Export Summary</span>
            </button>
          </div>
          
          <button
            onClick={handleRunAnother}
            className="btn-primary"
            style={{ padding: '10px 22px', fontSize: '13px', gap: '8px' }}
          >
            <RotateCcw size={13} />
            <span>Run Another Audit</span>
          </button>
        </div>
      </section>

      {/* Floating Toast Message */}
      {toastMessage && (
        <div className="premium-toast animate-toast">
          <Check size={14} />
          <span>{toastMessage}</span>
        </div>
      )}
    </div>
  );
}
